// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtT8Iw8EBP99AVJeJtHkS2fRSXVW-qrNA',
    appId: '1:312029247423:android:b51504efd2707758fd930a',
    messagingSenderId: '312029247423',
    projectId: 'nationalwaterfcm-4cd9e',
    storageBucket: 'nationalwaterfcm-4cd9e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAclW3WQarY3wGIkfURuuUHrW4VvViqIlM',
    appId: '1:312029247423:web:a8fb50af59b3cea2fd930a',
    messagingSenderId: '312029247423',
    projectId: 'nationalwaterfcm-4cd9e',
    authDomain: 'nationalwaterfcm-4cd9e.firebaseapp.com',
    storageBucket: 'nationalwaterfcm-4cd9e.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6wAPCqM5v6WEwuLhxZwcTLJPKYI-9idw',
    appId: '1:312029247423:ios:e872b31d10ebda34fd930a',
    messagingSenderId: '312029247423',
    projectId: 'nationalwaterfcm-4cd9e',
    storageBucket: 'nationalwaterfcm-4cd9e.appspot.com',
    iosBundleId: 'com.example.waterCustomerApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6wAPCqM5v6WEwuLhxZwcTLJPKYI-9idw',
    appId: '1:312029247423:ios:e872b31d10ebda34fd930a',
    messagingSenderId: '312029247423',
    projectId: 'nationalwaterfcm-4cd9e',
    storageBucket: 'nationalwaterfcm-4cd9e.appspot.com',
    iosBundleId: 'com.example.waterCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAclW3WQarY3wGIkfURuuUHrW4VvViqIlM',
    appId: '1:312029247423:web:f00b288221a4062ffd930a',
    messagingSenderId: '312029247423',
    projectId: 'nationalwaterfcm-4cd9e',
    authDomain: 'nationalwaterfcm-4cd9e.firebaseapp.com',
    storageBucket: 'nationalwaterfcm-4cd9e.appspot.com',
  );

}